apiVersion: apps/v1
kind: Deployment
metadata:
  name: merch-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merch-service
  template:
    metadata:
      labels:
        app: merch-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5003"
    spec:
      containers:
        - name: merch-service
          image: rajatsood1/merch-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
          envFrom:
            - configMapRef:
                name: merch-service-config
            - secretRef:
                name: merch-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: merch-service
spec:
  selector:
    app: merch-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
