apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5004"
    spec:
      containers:
        - name: order-service
          image: rajatsood1/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5004
          envFrom:
            - configMapRef:
                name: order-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
