apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5006"
    spec:
      containers:
        - name: review-service
          image: rajatsood1/review-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5006
          envFrom:
            - configMapRef:
                name: review-service-config
            - secretRef:
                name: review-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  selector:
    app: review-service
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
