name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build all backend services
        run: |
          docker-compose build
      - name: Build frontend
        run: |
          docker build -t eventmerch-frontend ./frontend
      # Uncomment below if you add tests
      # - name: Run backend tests
      #   run: |
      #     docker-compose run --rm auth-service npm test
      #     docker-compose run --rm event-service npm test
      #     docker-compose run --rm merch-service npm test
      #     docker-compose run --rm order-service npm test
