name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Create .env files for all services
        run: |
          echo "PORT=5000" > backend/gateway/.env
          echo "MONGO_URI=${{ secrets.GATEWAY_MONGO_URI }}" >> backend/gateway/.env
          echo "JWT_SECRET=${{ secrets.GATEWAY_JWT_SECRET }}" >> backend/gateway/.env

          echo "PORT=5001" > backend/auth-service/.env
          echo "MONGO_URI=${{ secrets.AUTH_MONGO_URI }}" >> backend/auth-service/.env
          echo "JWT_SECRET=${{ secrets.AUTH_JWT_SECRET }}" >> backend/auth-service/.env

          echo "PORT=5002" > backend/event-service/.env
          echo "MONGO_URI=${{ secrets.EVENT_MONGO_URI }}" >> backend/event-service/.env
          echo "JWT_SECRET=${{ secrets.EVENT_JWT_SECRET }}" >> backend/event-service/.env

          echo "PORT=5003" > backend/merch-service/.env
          echo "MONGO_URI=${{ secrets.MERCH_MONGO_URI }}" >> backend/merch-service/.env
          echo "JWT_SECRET=${{ secrets.MERCH_JWT_SECRET }}" >> backend/merch-service/.env

          echo "PORT=5004" > backend/order-service/.env
          echo "MONGO_URI=${{ secrets.ORDER_MONGO_URI }}" >> backend/order-service/.env
          echo "JWT_SECRET=${{ secrets.ORDER_JWT_SECRET }}" >> backend/order-service/.env

          echo "PORT=5005" > backend/payment-service/.env
          echo "MONGO_URI=${{ secrets.PAYMENT_MONGO_URI }}" >> backend/payment-service/.env
          echo "JWT_SECRET=${{ secrets.PAYMENT_JWT_SECRET }}" >> backend/payment-service/.env

          echo "PORT=5006" > backend/review-service/.env
          echo "MONGO_URI=${{ secrets.REVIEW_MONGO_URI }}" >> backend/review-service/.env
          echo "JWT_SECRET=${{ secrets.REVIEW_JWT_SECRET }}" >> backend/review-service/.env

          echo "VITE_API_URL=${{ secrets.FRONTEND_API_URL }}" > frontend/.env

      - name: Build and push auth-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/auth-service
          file: ./backend/auth-service/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/auth-service:latest

      - name: Build and push event-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/event-service
          file: ./backend/event-service/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/event-service:latest

      - name: Build and push merch-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/merch-service
          file: ./backend/merch-service/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/merch-service:latest

      - name: Build and push order-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/order-service
          file: ./backend/order-service/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/order-service:latest

      - name: Build and push payment-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/payment-service
          file: ./backend/payment-service/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/payment-service:latest

      - name: Build and push review-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/review-service
          file: ./backend/review-service/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/review-service:latest

      - name: Build and push gateway
        uses: docker/build-push-action@v5
        with:
          context: ./backend/gateway
          file: ./backend/gateway/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/gateway:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/frontend:latest

  deploy-to-eks:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/
